name: Code Check

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: ⚡ Install Dependencies (pnpm)
        run: pnpm install

      - name: 🔬 Run ESLint
        run: pnpm lint:strict

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: ⚡ Install Dependencies (pnpm)
        run: pnpm install

      - name: ⚙️ Build content-collections
        run: npx content-collections build

      - name: 🔎 Run Type Check
        run: pnpm typecheck

  prettier:
    name: 💅 Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: ⚡ Install Dependencies (pnpm)
        run: pnpm install

      - name: 💅 Run Prettier write
        run: pnpm format:write
